### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by xinzhichao** [JingwenWang95/DSP-SLAM#3] opened 2021-12-14 09:24 UTC
Hello, this is a great job. When I run this program, a segfault occurs. I modified the path in config_kitti.json according to the config file in your program, and the environment compiles without any errors. May I ask this What could be the reason?

**Comment by xinzhichao** [comment] 2021-12-14 09:56
But when i run  Freiburg Cars dataset ,is no problems.

**Comment by xinzhichao** [comment] 2021-12-14 09:57
But when i run Freiburg Cars dataset using dsp_slam_mono,is no problems.

**Comment by JingwenWang95** [comment] 2021-12-14 10:15
Hi! Thanks for your interest! It's a bit hard to tell what's happenning as multiple reasons might cause Segfault. Can you please attach your error message?

But given your description, I suspect it might be caused by the installation of mmdetection3d, as only KITTI sequence use 3D detector. Have you run the building script when buiilding DSP-SLAM or have you followed all the steps as in the buidling script?

**Comment by JingwenWang95** [comment] 2021-12-20 09:55
I will close this as there is no updates for a long time.

**Closed by JingwenWang95** 2021-12-20 09:55 UTC
